---
- hosts: main
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python 3'
      raw: sudo apt-get -y install python3-minimal
  tasks:
  - import_tasks: tasks/management.yml
  - import_tasks: tasks/users.yml
